pydv/curve.py
pydv/pdv.py
pydv/pydvpy.py

Resolves #1 and #2. Worked with Eric Shi to implement these commands like Ultra.

Updated the convol commands

---

setup.py

Small fixes to the setup.py file to open the proper file for the long_description, and update the version information to the most recent tag.  I was successful in writing a Spackage for PyDV, which I will commit upstream if you accept this PR.

README.rst -> README.md; 2.4.1 -> 2.4.2

---

pydv/pydvpy.py

Changed mode to 'full' for the convol commands 

---

pydv/curve.py
pydv/pdv.py
pydv/pydvpy.py

Updated the derivative command to use numpy's gradient method to handle boundary points correctly. Small code cleanup.

Updated the derivative command to use numpy's gradient method

---

pydv/curve.py
pydv/pdv.py
pydv/pydvpy.py

Updated the derivative command to use numpy's gradient method to handle boundary points correctly. Small code cleanup.

Updated the derivative command

---

pydv/pdv.py

Resolves #5. Allow control of grid color, style, and size.

---

pydv/pdv.py
pydv/pydvpy.py

Merge from 2.4 dev

---

pydv/pdv.py
pydv/pdvutil.py
pydv/pydvpy.py

Resolves #8. rev command implemented.

Resolves #8. rev command implemented.

---

pydv/pdv.py
pydv/pydvpy.py

Resolves #7. Implemented the random command. Also removed the markers for the sort and reverse commands.

Resolves #7. Implemented the random command.

---

pydv/pdv.py

Added the capability to make minor tick marks visible, change their length and width, and change their color per axis. 
Also changed the default label length from 25 to 50 characters long.

Resolves #10. Add minor tick functionality to PyDV.

---

pydv/pydvpy.py
pydv/tests/testPC.txt

Added additional points to create histogram instead of using drawing style. Updated the sample piece-wise constant test data file.

Resolves #23. Fix the piece-wise constant integration bug.

---

pydv/curve.py
pydv/pdv.py
pydv/pdvplot.py
pydv/pydvpy.py

Resolves #85. Fixed the appendcurves command and updated version info.

Fixed the appendcurves command and updated version info.

---

pydv/pdv.py
pydv/pdvplot.py
pydv/pydvpy.py

Minor changes/cleanup in support of #76

Minor changes/cleanup for python 3 refactoring

---

pydv/pdv.py

Fixed guilims command

---

pydv/pdv.py

guilims command fix. Merged from master.

---

pydv/pdv.py

Fixed and updated the jn and jnx commands.

---

pydv/pdvplot.py

Resolves #127. Updated the About PyDV message box link.

Updated the About PyDV message box link.

---

pydv/pdv.py
pydv/pdvutil.py

Resolves #131. Fixed the @ symbol range bug.

Fixed the @ symbol range bug.

---

pydv/docs/plot_control_cmds.rst
pydv/pdv.py

Resolves #135. Added border command.

Added border command.

---

pydv/docs/math_operations.rst
pydv/pdv.py

Resolves #134. Enhanced add, subtract, divide and multiply commands to support dividing by a real number.

Enhanced add, subtract, divide and multiply commands to divide by real number

---

pydv/docs/plot_control_cmds.rst
pydv/pdv.py

Resolves #4. Also made labelfilenames command all lowercase and minorcode cleanup.

Added curve letter to legend label

---

LICENSE
pydv/curve.py
pydv/pdv.py
pydv/pdvnavbar.py
pydv/pdvplot.py
setup.py

Resolves #144. Minor updates to copyright year and version.

Persist UI Zoom settings

---

pydv/pdv.py

Resolves #77. Created menur and listr commands that allow start and stop indices for listing curves and plots.

 Created menur and listr commands

---

pydv/pdv.py
pydv/pdvplot.py

Resolves #24. Added `plotlayout` command to adjust plot layout parameters.

Added plotlayout command to adjust plot layout parameters.

---

pydv/docs/env_inquiry_cmds.rst
pydv/docs/index.rst
pydv/docs/plot_control_cmds.rst
pydv/docs/pydv.rst

Updated docs for the addition of the listr, menur, and plotlayout commands.

Updated docs

---

pydv/docs/plot_control_cmds.rst
pydv/pdv.py

Resolves #177. Added the transparent and dpi options to the image command so images can be saved with transparency and different resolutions.

Added the transparent and dpi options to the image command

---

pydv/docs/math_operations.rst
pydv/pdv.py

Added the add_h command that allows the mathematical addition of curves that have been read in from a file but not yet plotted. Updated documentation.

Added the add_h command

---

pydv/docs/math_operations.rst
pydv/pdv.py

Resolves #154. Added the subtract, multiply and divide commands that allow simple math operations on curves that have been read in but not yet plotted.

 Added the subtract_h, multiply_h and divide_h commands

---

pydv/docs/io_commands.rst
pydv/pdv.py
pydv/pydvpy.py

Pydv sina integration

---

pydv/curve.py
pydv/docs/io_commands.rst
pydv/pdv.py
pydv/pydvpy.py

Pydv 197 plot attributes with curves

---

pydv/curve.py
pydv/docs/plot_control_cmds.rst
pydv/pdv.py

Pydv 203 add and remove curves from legend

---

pydv/curve.py

Force interp num to be integers

---

.github/pull_request_template.md

Resolves #238
Added the checklist item for running the wsc tests on the rz as well as the image tests.

Added checklist item for running WSC test
